[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'cd backend && npm ci --production=false',
  'cd backend && npx prisma generate'
]

[phases.build]
cmds = ['cd backend && npm run build']

[start]
cmd = 'cd backend && node dist/main'